### ISSUE TITLE
Do you want go one step further, by estimating the position of iris where is looking at?

### ISSUE THREAD

**Issue by Asadullah-Dal17** [alireza787b/Python-Gaze-Face-Tracker#1]
- Accurately estimate position iris 
- Detection Blinks 
- Counting the blinks.

**Comment by alireza787b** [comment]
hi Asadullah
Great Idea... maybe do this... 
accurately estimating what he is looking for needs another source of data of the environment and calibrating based on that.. but for the blink estimator actually it's a good idea. I might add that soon...
thanks 
by the way thanks for the initial code. it helped me alot .

**Comment by Asadullah-Dal17** [comment]
You need only blink detector, right?

**Comment by alireza787b** [comment]
> You need only blink detector, right?
> 

Sorry to re open, but just remembered sth..
Did you check the headPos bran in h which I implemented facial orientation irealal time? 
I am trying to implement mechaism to see what is the targ is t seeing right now.. have you done anything for that?

**Comment by Asadullah-Dal17** [comment]
Okay. got you.
